// Resource index for CRM Template Base Server
import { loadResource } from '../utils/resource-loader.js';

export const resources = {
  'ui-system/dialog-patterns': () => loadResource('ui-system/dialog-patterns.js'),
  'ui-system/configuration-tabs-pattern': () => loadResource('ui-system/configuration-tabs-pattern.js'),
  'architecture/modular-forms-system': () => loadResource('architecture/modular-forms-system.js'),
  'architecture/feature-based-organization': () => loadResource('architecture/feature-based-organization.js'),
  'architecture/reference-architecture-standards': () => loadResource('architecture/reference-architecture-standards.js'),
  'architecture/table-architecture-types': () => loadResource('architecture/table-architecture-types.js'),
  'routing/nextjs-advanced-patterns': () => loadResource('routing/nextjs-advanced-patterns.js'),
  'development/typescript-excellence': () => loadResource('development/typescript-excellence.js'),
  'development/technical-implementation-guides': () => loadResource('development/technical-implementation-guides.js'),
  'components/enterprise-component-patterns': () => loadResource('components/enterprise-component-patterns.js'),
  'components/universal-table-search-pattern': () => loadResource('components/universal-table-search-pattern.js'),
  'components/hybrid-datatable-pattern': () => loadResource('components/hybrid-datatable-pattern.js'),
  'i18n/internationalization-patterns': () => loadResource('i18n/internationalization-patterns.js'),
  'architecture/advanced-form-architecture': () => loadResource('architecture/advanced-form-architecture.js'),
  'development/advanced-date-filtering': () => loadResource('development/advanced-date-filtering.js'),
  'routing/parallel-routes-implementation': () => loadResource('routing/parallel-routes-implementation.js'),
  'development/quality-assurance-workflow': () => loadResource('development/quality-assurance-workflow.js'),
  'operations/server-side-table-integration': () => loadResource('operations/server-side-table-integration.js'),
  'reference/definitive-reference-implementation': () => loadResource('reference/definitive-reference-implementation.js'),
  'patterns/unified-pattern-library': () => loadResource('patterns/unified-pattern-library.js'),
  'bundles/chat-page-bundle': () => loadResource('bundles/chat-page-bundle.js'),
  'chat-bundle/quick-reference': () => loadResource('chat-bundle/quick-reference.js'),
  'bundles/design-system-bundle': () => loadResource('bundles/design-system-bundle.js'),
  'bundles/dialog-bundle': () => loadResource('bundles/dialog-bundle.js'),
  'dialog-bundle/components/foundation-patterns': () => loadResource('dialog-bundle/components/foundation-patterns.js'),
  'dialog-bundle/components/confirmation-dialogs': () => loadResource('dialog-bundle/components/confirmation-dialogs.js'),
  'dialog-bundle/quick-reference': () => loadResource('dialog-bundle/quick-reference.js'),
  'bundles/form-bundle': () => loadResource('bundles/form-bundle.js'),
  'form-bundle/components/page-structure': () => loadResource('form-bundle/components/page-structure.js'),
  'form-bundle/components/input-patterns': () => loadResource('form-bundle/components/input-patterns.js'),
  'form-bundle/components/button-patterns': () => loadResource('form-bundle/components/button-patterns.js'),
  'form-bundle/components/validation-patterns': () => loadResource('form-bundle/components/validation-patterns.js'),
  'form-bundle/components/layout-patterns': () => loadResource('form-bundle/components/layout-patterns.js'),
  'form-bundle/components/feedback-patterns': () => loadResource('form-bundle/components/feedback-patterns.js'),
  'form-bundle/templates/standalone-form': () => loadResource('form-bundle/templates/standalone-form.js'),
  'form-bundle/templates/multi-step-form': () => loadResource('form-bundle/templates/multi-step-form.js'),
  'form-bundle/templates/critical-patterns': () => loadResource('form-bundle/templates/critical-patterns.js'),
  'form-bundle/quick-reference': () => loadResource('form-bundle/quick-reference.js'),
  'bundles/notification-page-bundle': () => loadResource('bundles/notification-page-bundle.js'),
  'notification-bundle/quick-reference': () => loadResource('notification-bundle/quick-reference.js'),
  'bundles/table-page-bundle': () => loadResource('bundles/table-page-bundle.js'),
  'table-bundle/quick-reference': () => loadResource('table-bundle/quick-reference.js'),
};